services:
  maltslist:
    network_mode: "host"
    tty: true
    build:
      dockerfile: Dockerfile
    image: maltslist
    restart: always
    volumes:
      - ./src:/var/www/src
      - ./db:/var/www/src/db
    environment:
      DATABASE: ${DATABASE}
      TMDB_API_KEY: ${TMDB_API_KEY}
      TMDB_INCLUDE_ADULT: ${TMDB_INCLUDE_ADULT}
